# Generated by Django 5.2 on 2025-11-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studybuddy", "0004_room_timer_duration_room_timer_is_running_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="access_code",
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="room",
            name="is_private",
            field=models.BooleanField(default=False),
        ),
    ]
