# Generated by Django 5.2 on 2025-11-07 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("studybuddy", "0005_room_access_code_room_is_private"),
    ]

    operations = [
        migrations.RenameField(
            model_name="room",
            old_name="access_code",
            new_name="join_code",
        ),
    ]
