# Generated by Django 5.2.7 on 2025-11-11 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studybuddy", "0005_userprofile_bio_userprofile_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="is_private",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="room",
            name="password",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
