# Generated by Django 5.2 on 2025-11-10 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("studybuddy", "0005_userprofile_bio_userprofile_location_and_more"),
        ("studybuddy", "0006_rename_access_code_room_join_code"),
    ]

    operations = []
