# Generated by Django 5.2 on 2025-11-10 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("studybuddy", "0007_merge_20251110_1114"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="is_private",
        ),
        migrations.RemoveField(
            model_name="room",
            name="join_code",
        ),
    ]
